Add verify to picotool load command
arduino/rp2040tools pull request #6
Opened 2021-04-21 08:19 UTC by facchinm

This is needed to debug early flash failures

2022-05-23 08:48 UTC, per1234 requested changes

2022-05-23 08:48 UTC, per1234 commented on main.go
> +	load := []string{filepath.Join(path, "picotool"), "load -v", *binary + ".uf2"}
```suggestion
	load := []string{filepath.Join(path, "picotool"), "load", "-v", *binary + ".uf2"}
```

The previous code produces an invalid command (i.e., `picotool "load -v"`):

```text
Unknown command: load -v
```

2022-05-29 12:39 UTC, per1234 requested changes
Verification should be toggled via an `rp2040load` command line flag.

The verification time might be significant with the very large programs that are possible with this board.

The Arduino boards platform framework and development software has a dedicated system for controlling the upload verification. It would be silly for Arduino to skip supporting it in the tools we created:

https://arduino.github.io/arduino-cli/dev/platform-specification/#upload-verification

2022-05-30 07:40 UTC, facchinm commented
@per1234 you are right, the `verify` command should be added to the wrapper commandline and passed only if {verify} is specified in the core. Updating the PR right now

2022-05-31 05:59 UTC, per1234 approved these changes
Very nice improvement to the tool. Thanks @facchinm!

2022-05-31 09:49 UTC, merged